/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jakik.guikalkulatorbd;

/**
 *
 * @author excee
 */
public class KalkulatorBD extends javax.swing.JFrame {

double panjang, lebar, luas, keliling, sisi, luaspersegi, kelilingpersegi, alas, tinggi, sisimiring, luassegitiga, kelsegitiga;
    /**
     * Creates new form KalkulatorBD
     */
    public KalkulatorBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtkalkulator = new javax.swing.JLabel();
        txtpersegi = new javax.swing.JLabel();
        areasisipersegi = new javax.swing.JLabel();
        fieldsisipersegi = new javax.swing.JTextField();
        txtpersegipanjang = new javax.swing.JLabel();
        txtpanjangpp = new javax.swing.JLabel();
        fieldpanjangpp = new javax.swing.JTextField();
        txtlebarpp = new javax.swing.JLabel();
        fieldlebarpp = new javax.swing.JTextField();
        txthasilpersegi = new javax.swing.JLabel();
        txthasilpp = new javax.swing.JLabel();
        btnhitungpp = new javax.swing.JButton();
        txthasilluaspp = new javax.swing.JLabel();
        TFhasilluaspp = new javax.swing.JTextField();
        TXThasilkelilingpp = new javax.swing.JLabel();
        TFhasilkelilingpp = new javax.swing.JTextField();
        TXTluaspersegi = new javax.swing.JLabel();
        TFhasilluaspersegi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TFhasilkelpersegi = new javax.swing.JTextField();
        TXTSSS = new javax.swing.JLabel();
        TXTAlasSSS = new javax.swing.JLabel();
        TFalasSSS = new javax.swing.JTextField();
        TXTTinggiSSS = new javax.swing.JLabel();
        TFtinggiSSS = new javax.swing.JTextField();
        TXTsisimiringSSS = new javax.swing.JLabel();
        TFsisimiringSSS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXTluasSSS = new javax.swing.JLabel();
        TFhasilluasSSS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFhasilkelilingSSS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtkalkulator.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtkalkulator.setText("Kalkulator Bangun Datar");

        txtpersegi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpersegi.setText("Persegi");

        areasisipersegi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areasisipersegi.setText("Masukkan Sisi");

        fieldsisipersegi.setBackground(new java.awt.Color(255, 204, 204));
        fieldsisipersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldsisipersegiActionPerformed(evt);
            }
        });

        txtpersegipanjang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpersegipanjang.setText("Persegi Panjang");

        txtpanjangpp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpanjangpp.setText("Masukkan Panjang");

        fieldpanjangpp.setBackground(new java.awt.Color(255, 255, 204));
        fieldpanjangpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpanjangppActionPerformed(evt);
            }
        });

        txtlebarpp.setText("Masukkan Lebar");

        fieldlebarpp.setBackground(new java.awt.Color(255, 255, 204));
        fieldlebarpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldlebarppActionPerformed(evt);
            }
        });

        txthasilpersegi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txthasilpersegi.setText("Hasil");

        txthasilpp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txthasilpp.setText("Hasil");

        btnhitungpp.setBackground(new java.awt.Color(51, 255, 255));
        btnhitungpp.setText("Hitung");
        btnhitungpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungppActionPerformed(evt);
            }
        });

        txthasilluaspp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txthasilluaspp.setText("Luas");

        TFhasilluaspp.setBackground(new java.awt.Color(51, 255, 255));
        TFhasilluaspp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFhasilluasppActionPerformed(evt);
            }
        });

        TXThasilkelilingpp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXThasilkelilingpp.setText("Keliling");

        TFhasilkelilingpp.setBackground(new java.awt.Color(51, 255, 255));

        TXTluaspersegi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTluaspersegi.setText("Luas");

        TFhasilluaspersegi.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setText("Keliling");

        TFhasilkelpersegi.setBackground(new java.awt.Color(51, 255, 255));
        TFhasilkelpersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFhasilkelpersegiActionPerformed(evt);
            }
        });

        TXTSSS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TXTSSS.setText("Segitiga Siku-Siku");

        TXTAlasSSS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTAlasSSS.setText("Masukkan Alas");

        TFalasSSS.setBackground(new java.awt.Color(204, 255, 204));
        TFalasSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFalasSSSActionPerformed(evt);
            }
        });

        TXTTinggiSSS.setText("Masukkan Tinggi");

        TFtinggiSSS.setBackground(new java.awt.Color(204, 255, 204));
        TFtinggiSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtinggiSSSActionPerformed(evt);
            }
        });

        TXTsisimiringSSS.setText("Masukkan Sisi Miring");

        TFsisimiringSSS.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Hasil");

        TXTluasSSS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTluasSSS.setText("Luas");

        TFhasilluasSSS.setBackground(new java.awt.Color(51, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Keliling");

        TFhasilkelilingSSS.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(txtpersegi)
                .addGap(170, 170, 170)
                .addComponent(txtpersegipanjang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TXTSSS)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(areasisipersegi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldsisipersegi)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFhasilkelpersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TXTluaspersegi)
                                .addGap(18, 18, 18)
                                .addComponent(TFhasilluaspersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(txthasilpersegi)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(txtkalkulator)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(txtlebarpp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(btnhitungpp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(162, 162, 162)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtpanjangpp)
                                        .addComponent(fieldpanjangpp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldlebarpp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txthasilpp)
                                            .addGap(38, 38, 38))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(txthasilluaspp)
                                            .addGap(18, 18, 18)
                                            .addComponent(TFhasilluaspp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TXThasilkelilingpp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TFhasilkelilingpp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TXTTinggiSSS)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TXTsisimiringSSS)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TFtinggiSSS)
                                        .addComponent(TFsisimiringSSS)
                                        .addComponent(TFalasSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(TXTAlasSSS)
                                        .addGap(47, 47, 47))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TXTluasSSS)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFhasilkelilingSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFhasilluasSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(77, 77, 77)))
                                .addGap(64, 64, 64))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtkalkulator)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpersegi)
                            .addComponent(txtpersegipanjang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areasisipersegi)
                            .addComponent(txtpanjangpp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldpanjangpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldsisipersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtlebarpp)
                        .addGap(18, 18, 18)
                        .addComponent(fieldlebarpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txthasilpp)
                                    .addComponent(txthasilpersegi))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txthasilluaspp, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TFhasilluaspp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TFhasilkelilingpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXThasilkelilingpp)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFhasilluaspersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXTluaspersegi, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TFhasilkelpersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnhitungpp)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TXTSSS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTAlasSSS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFalasSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTTinggiSSS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFtinggiSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(TXTsisimiringSSS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFsisimiringSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTluasSSS)
                            .addComponent(TFhasilluasSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFhasilkelilingSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldsisipersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldsisipersegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldsisipersegiActionPerformed

    private void fieldpanjangppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpanjangppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldpanjangppActionPerformed

    private void fieldlebarppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldlebarppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldlebarppActionPerformed

    private void btnhitungppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungppActionPerformed
        // TODO add your handling code here:
        panjang = Double.parseDouble(fieldpanjangpp.getText());
        lebar = Double.parseDouble(fieldlebarpp.getText());
        luas = panjang*lebar;
        keliling = 2*(panjang+lebar);
        TFhasilluaspp.setText(String.valueOf(luas));
        TFhasilkelilingpp.setText(String.valueOf(keliling));
        sisi = Double.parseDouble(fieldsisipersegi.getText());
        luaspersegi = sisi*sisi;
        kelilingpersegi = 4*sisi;
        TFhasilluaspersegi.setText(String.valueOf(luaspersegi));
        TFhasilkelpersegi.setText(String.valueOf(kelilingpersegi));
        alas = Double.parseDouble(TFalasSSS.getText());
        tinggi = Double.parseDouble(TFtinggiSSS.getText());
        sisimiring = Double.parseDouble(TFsisimiringSSS.getText());
        luassegitiga = alas*tinggi/2;
        kelsegitiga = alas + tinggi + sisimiring;
        TFhasilluasSSS.setText(String.valueOf(luassegitiga));
        TFhasilkelilingSSS.setText(String.valueOf(kelsegitiga));
    }//GEN-LAST:event_btnhitungppActionPerformed

    private void TFhasilluasppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFhasilluasppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFhasilluasppActionPerformed

    private void TFalasSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFalasSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFalasSSSActionPerformed

    private void TFtinggiSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtinggiSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFtinggiSSSActionPerformed

    private void TFhasilkelpersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFhasilkelpersegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFhasilkelpersegiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFalasSSS;
    private javax.swing.JTextField TFhasilkelilingSSS;
    private javax.swing.JTextField TFhasilkelilingpp;
    private javax.swing.JTextField TFhasilkelpersegi;
    private javax.swing.JTextField TFhasilluasSSS;
    private javax.swing.JTextField TFhasilluaspersegi;
    private javax.swing.JTextField TFhasilluaspp;
    private javax.swing.JTextField TFsisimiringSSS;
    private javax.swing.JTextField TFtinggiSSS;
    private javax.swing.JLabel TXTAlasSSS;
    private javax.swing.JLabel TXTSSS;
    private javax.swing.JLabel TXTTinggiSSS;
    private javax.swing.JLabel TXThasilkelilingpp;
    private javax.swing.JLabel TXTluasSSS;
    private javax.swing.JLabel TXTluaspersegi;
    private javax.swing.JLabel TXTsisimiringSSS;
    private javax.swing.JLabel areasisipersegi;
    private javax.swing.JButton btnhitungpp;
    private javax.swing.JTextField fieldlebarpp;
    private javax.swing.JTextField fieldpanjangpp;
    private javax.swing.JTextField fieldsisipersegi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txthasilluaspp;
    private javax.swing.JLabel txthasilpersegi;
    private javax.swing.JLabel txthasilpp;
    private javax.swing.JLabel txtkalkulator;
    private javax.swing.JLabel txtlebarpp;
    private javax.swing.JLabel txtpanjangpp;
    private javax.swing.JLabel txtpersegi;
    private javax.swing.JLabel txtpersegipanjang;
    // End of variables declaration//GEN-END:variables
}
